In [ ]:
import pandas as pd
import nltk.corpus
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
df = pd.read_csv('File_1.csv')

In [ ]:
stop_words = stopwords.words('english')
df['Text_No_stopwords'] = df['Text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

In [ ]:
df[['Text', 'Text_No_stopwords']].head(5)

,Text,Text_No_stopwords
0,"In order to replicate their experiment, you wo...","In order replicate experiment, would need know..."
1,"After reading the group's procedures, I would ...","After reading group's procedures, I would need..."
2,"To replicate the group's experiment, the proce...","To replicate group's experiment, procedure wou..."
3,Information that would be required to replicat...,Information would required replicate experimen...
4,The procedure is very unclear. In order to rep...,The procedure unclear. In order replicate expe...

In [ ]:
df.to_csv('File_2.csv', encoding = 'utf-8', index = False)

In [ ]:
filename = input("Answers.csv")
 
 
def remove_punc(string):
    punc = '''!()-[]{};:'"\, <>./?@#$%^&*_~'''
    for ele in string:  
        if ele in punc:  
            string = string.replace(ele, "") 
    return string
 
 
try:
    with open(filename,'r',encoding="utf-8") as f:
        data = f.read()
    with open(filename,"w+",encoding="utf-8") as f:
        f.write(remove_punc(data))
    print("Removed punctuations from the file", filename)
except FileNotFoundError:
    print("File not found")

Answers.csvh
File not found

In [ ]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize, word_tokenize
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

In [ ]:
import textblob
from textblob import TextBlob
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
from functools import reduce
import operator
import collections
from collections import Counter

In [ ]:
import datetime as dt

In [ ]:
import seaborn as sns

import matplotlib.pyplot as plt

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('test.csv')

In [ ]:
df.head()

     Id  EssaySet  Score                                          EssayText
0  1673         1      1  The procedures I think they should have includ...
1  1674         1      1  In order to replicate this experiment, you wou...
2  1675         1      3  In order to replicate their experiment, you wo...
3  1676         1      0  Pleace a simple of one material into one conta...
4  1677         1      0  Determin the mass of four different samples ma...

In [ ]:
def preprocessing(text):

# removing punctuations, unwanted characters and converting to lowercase

  text = re.sub("[^-9A-Za-z ]", "", text).lower()

# removing stopwords and tokenizing

  stop = stopwords.words("english")

  tokens = [word for word in (token for token in word_tokenize(text)) if word not in stop]

# lemmatizing

  lmtzr = nltk.WordNetLemmatizer()

  preprocessed_text = ' '.join([lmtzr.lemmatize(word) for word in tokens])

  return preprocessed_text

In [ ]:
df['EssayText'] = df['EssayText'].astype(str)
df['PP_EssayText'] = df['EssayText'].apply(preprocessing)

In [ ]:
df['t_PP_EssayText'] = df.apply(lambda row:  nltk.word_tokenize(row['PP_EssayText']), axis=1)
df['POS_Tags'] = df.apply(lambda row: nltk.pos_tag(row['t_PP_EssayText']), axis=1)

In [ ]:
# functions for separating the POS Tags
def adjectives(text):
    blob = TextBlob(text)
    return [word for (word,tag) in blob.tags if tag == 'JJ']
def verbs(text):
    blob = TextBlob(text)
    return [word for (word,tag) in blob.tags if tag.startswith('VB')]
def adverbs(text):
    blob = TextBlob(text)
    return [word for (word,tag) in blob.tags if tag.startswith('RB')]
def nouns(text):
    blob = TextBlob(text)
    return [word for (word,tag) in blob.tags if tag.startswith('NN')]

In [ ]:
df['Adjectives'] = df['PP_EssayText'].apply(adjectives)
df['Verbs'] = df['PP_EssayText'].apply(verbs)
df['Adverbs'] = df['PP_EssayText'].apply(adverbs)
df['Nouns'] = df['PP_EssayText'].apply(nouns)

In [ ]:
df[['POS_Tags', 'Adjectives', 'Verbs', 'Adverbs', 'Nouns']].head()

,POS_Tags,Adjectives,Verbs,Adverbs,Nouns
0,"[(procedure, NN), (think, NN), (included, VBD)...",[different],"[included, used]",[],"[procedure, think, inorder, replicate, experim..."
1,"[(order, NN), (replicate, NN), (experiment, NN...","[many, distilled]","[need, know, vinegar, used, obtained]",[much],"[order, replicate, experiment, ml, water, rins..."
2,"[(order, NN), (replicate, NN), (experiment, NN...","[much, marble, u, different, last, replicate, ...","[need, know, pouring, going, tell, sit, compro...","[well, specifically, also]","[order, replicate, experiment, vinegar, contai..."
3,"[(pleace, NN), (simple, JJ), (one, CD), (mater...","[simple, sample, single, single]","[label, remaining, placing]",[],"[pleace, material, container, repeat, sample, ..."
4,"[(determin, JJ), (mass, NN), (four, CD), (diff...","[determin, different, marble, mass, marble]",[starting],[],"[mass, sample, limestone, wood, plastic, end, ..."

In [ ]:
df['Unique Terms'] = df['PP_EssayText'].str.split().explode().drop_duplicates().groupby(level=0).apply(list)

In [ ]:
df[['EssayText', 'POS_Tags', 'Adjectives', 'Verbs', 'Adverbs', 'Nouns', 'Unique Terms']].head(1000)

,EssayText,POS_Tags,Adjectives,Verbs,Adverbs,Nouns,Unique Terms
0,The procedures I think they should have includ...,"[(procedure, NN), (think, NN), (included, VBD)...",[different],"[included, used]",[],"[procedure, think, inorder, replicate, experim...","[procedure, think, included, inorder, replicat..."
1,"In order to replicate this experiment, you wou...","[(order, NN), (replicate, NN), (experiment, NN...","[many, distilled]","[need, know, vinegar, used, obtained]",[much],"[order, replicate, experiment, ml, water, rins...","[order, need, know, many, ml, vinegar, much, d..."
2,"In order to replicate their experiment, you wo...","[(order, NN), (replicate, NN), (experiment, NN...","[much, marble, u, different, last, replicate, ...","[need, know, pouring, going, tell, sit, compro...","[well, specifically, also]","[order, replicate, experiment, vinegar, contai...","[pouring, container, well, kind, going, measur..."
3,Pleace a simple of one material into one conta...,"[(pleace, NN), (simple, JJ), (one, CD), (mater...","[simple, sample, single, single]","[label, remaining, placing]",[],"[pleace, material, container, repeat, sample, ...","[pleace, simple, one, label, repeat, remaining..."
4,Determin the mass of four different samples ma...,"[(determin, JJ), (mass, NN), (four, CD), (diff...","[determin, different, marble, mass, marble]",[starting],[],"[mass, sample, limestone, wood, plastic, end, ...","[determin, four, starting, end, diffrence]"
...,...,...,...,...,...,...,...
995,Pandas in China are similar to koalas in Austr...,"[(panda, NN), (china, NN), (similar, JJ), (koa...","[similar, bear]","[koala, australia, made]",[],"[panda, china, koala, australia, panda, eat, b...",NaN
996,Panda in China are similar to koalas in Austra...,"[(panda, NN), (china, NN), (similar, JJ), (koa...","[similar, habitat, different, u, cant, live]","[stay, give, addapt, give]",[],"[panda, china, koala, need, live, source, habi...","[caue, addapt]"
997,China's panda and Australia's koala are simila...,"[(china, NN), (panda, NN), (australia, IN), (k...","[similar, eucalyptus, animal, different]",[consume],[basically],"[china, panda, koala, type, plant, panda, eat,...",[consume]
998,Pandas and koalas are both the same because th...,"[(panda, NN), (koala, VBZ), (eat, VBP), (certa...","[certain, specialist, different]","[koala, eat]",[also],"[panda, thing, python, specialist, python, gen...",NaN
999,"As you can see, pandas in China are similar to...","[(see, VB), (panda, JJ), (china, NNS), (simila...","[panda, similar, leaf, different, panda, diffe...","[see, specialist, panda, eats, eucalyptus, koala]","[also, therefore, actually]","[china, koala, austria, animal, koala, herbivo...","[austria, herbivore, carnivore, eater]"